insert into subject (name, tutor) values ('Requirements Analysis', 'Betty');
insert into subject (name, tutor) values ('Networking', 'McGill');
insert into subject (name, tutor) values ('DP', 'Straffon');
insert into subject (name, tutor) values ('Twill', 'Emblen');
insert into subject (name, tutor) values ('Global Management', 'Messenbird');
insert into subject (name, tutor) values ('Image Editing', 'Weiser');
insert into subject (name, tutor) values ('MLOAD', 'Greenroa');
insert into subject (name, tutor) values ('Property Management Systems', 'Whitlock');
insert into subject (name, tutor) values ('Move Up Buyers', 'Dinsdale');
insert into subject (name, tutor) values ('AQL', 'Rogister');
insert into subject (name, tutor) values ('New Product Ideas', 'Frantz');
insert into subject (name, tutor) values ('Economic Research', 'Elwood');
insert into subject (name, tutor) values ('TDMA', 'McAteer');
insert into subject (name, tutor) values ('Post Production', 'Tiery');
insert into subject (name, tutor) values ('XForms', 'Mellings');
insert into subject (name, tutor) values ('LPCVD', 'Sherston');
insert into subject (name, tutor) values ('Ethernet', 'Dovidaitis');
insert into subject (name, tutor) values ('iPhone Support', 'Glewe');
insert into subject (name, tutor) values ('TPT', 'Enston');
insert into subject (name, tutor) values ('Performance Improvement', 'Redler');
insert into subject (name, tutor) values ('RDO', 'Burdon');
insert into subject (name, tutor) values ('Financial Risk', 'Bellenie');
insert into subject (name, tutor) values ('UTRAN', 'Oxlade');
insert into subject (name, tutor) values ('Windows NT', 'Tunsley');
insert into subject (name, tutor) values ('PCI DSS', 'Kinsett');
insert into subject (name, tutor) values ('CMDB', 'Lambal');
insert into subject (name, tutor) values ('Order Picking', 'Norquay');
insert into subject (name, tutor) values ('BMC Remedy Ticketing System', 'Vickarman');
insert into subject (name, tutor) values ('EHR', 'Jeggo');
insert into subject (name, tutor) values ('Crisis Communications', 'Divina');
insert into subject (name, tutor) values ('Iron', 'Bentame');
insert into subject (name, tutor) values ('LPR', 'Rosenhaupt');
insert into subject (name, tutor) values ('Pyrolysis', 'Bluett');
insert into subject (name, tutor) values ('WLM', 'Dunsmore');
insert into subject (name, tutor) values ('NVivo', 'Gibbons');
insert into subject (name, tutor) values ('TM1', 'Mattis');
insert into subject (name, tutor) values ('Product Development', 'Hammerman');
insert into subject (name, tutor) values ('FFT', 'Castellino');
insert into subject (name, tutor) values ('VSEO', 'Gendrich');
insert into subject (name, tutor) values ('Human Capital Management', 'Hake');
insert into subject (name, tutor) values ('Venture Capital', 'Zuker');
insert into subject (name, tutor) values ('XBR', 'Cobello');
insert into subject (name, tutor) values ('UHV', 'Hing');
insert into subject (name, tutor) values ('Medical Education', 'Bean');
insert into subject (name, tutor) values ('Technical Support', 'Bulbrook');
insert into subject (name, tutor) values ('WF', 'Betjes');
insert into subject (name, tutor) values ('Labor Relations', 'McCrudden');
insert into subject (name, tutor) values ('FFP', 'Hunn');
insert into subject (name, tutor) values ('Mood Boards', 'Nund');
insert into subject (name, tutor) values ('Eggs', 'Ors');
insert into subject (name, tutor) values ('Year-end Close', 'Dodell');
insert into subject (name, tutor) values ('Lubrication', 'Riglar');
insert into subject (name, tutor) values ('Oracle RAC', 'Pauli');
insert into subject (name, tutor) values ('Focus Groups', 'Dummett');
insert into subject (name, tutor) values ('IR', 'Sallier');
insert into subject (name, tutor) values ('XACT', 'Ivanikov');
insert into subject (name, tutor) values ('European Union', 'Grzegorczyk');
insert into subject (name, tutor) values ('VTK', 'Roote');
insert into subject (name, tutor) values ('Aquariums', 'Randleson');
insert into subject (name, tutor) values ('Government Contracting', 'Gardiner');
insert into subject (name, tutor) values ('Traditional IRA', 'While');
insert into subject (name, tutor) values ('Open XML', 'Cattle');
insert into subject (name, tutor) values ('Top Secret', 'Dobell');
insert into subject (name, tutor) values ('SQL*Plus', 'Byham');
insert into subject (name, tutor) values ('Negotiation', 'Antcliffe');
insert into subject (name, tutor) values ('Cyberlaw', 'Garrison');
insert into subject (name, tutor) values ('GDS', 'Dagnall');
insert into subject (name, tutor) values ('DG Sets', 'Elmhirst');
insert into subject (name, tutor) values ('Online Reputation Management', 'Bartkiewicz');
insert into subject (name, tutor) values ('MBOX', 'Binyon');
insert into subject (name, tutor) values ('FFT', 'MacCardle');
insert into subject (name, tutor) values ('Contact Centers', 'Harty');
insert into subject (name, tutor) values ('Lyricist', 'Lamb');
insert into subject (name, tutor) values ('Power Systems', 'Ricca');
insert into subject (name, tutor) values ('Job Scheduling', 'Filson');
insert into subject (name, tutor) values ('Data Structures', 'Cudiff');
insert into subject (name, tutor) values ('PPV', 'Menico');
insert into subject (name, tutor) values ('NMT', 'Gladding');
insert into subject (name, tutor) values ('XML', 'Luckin');
insert into subject (name, tutor) values ('FPA', 'Wilgar');
insert into subject (name, tutor) values ('European Politics', 'Habbershon');
insert into subject (name, tutor) values ('cXML', 'Hulks');
insert into subject (name, tutor) values ('Rock Mechanics', 'Innwood');
insert into subject (name, tutor) values ('Process Engineering', 'Fenelon');
insert into subject (name, tutor) values ('RWA', 'Buffey');
insert into subject (name, tutor) values ('Lumion', 'Lempenny');
insert into subject (name, tutor) values ('Western Europe', 'Manketell');
insert into subject (name, tutor) values ('RDL', 'Van Schafflaer');
insert into subject (name, tutor) values ('Permanent Placement', 'Shortan');
insert into subject (name, tutor) values ('Professional Liability', 'Traviss');
insert into subject (name, tutor) values ('Vacation', 'Habershaw');
insert into subject (name, tutor) values ('SAP-SD', 'Yelland');
insert into subject (name, tutor) values ('Ion Exchange', 'Wilcocks');
insert into subject (name, tutor) values ('European Law', 'Ruperti');
insert into subject (name, tutor) values ('Creative Writing', 'Wenman');
insert into subject (name, tutor) values ('LUSAS', 'Keiling');
insert into subject (name, tutor) values ('CNN Newsource', 'Shiel');
insert into subject (name, tutor) values ('Erlang', 'Philipsson');
insert into subject (name, tutor) values ('HTML5', 'Kinnie');
insert into subject (name, tutor) values ('CBP', 'Cabbell');
insert into subject (name, tutor) values ('WHIMS', 'Phillot');
insert into subject (name, tutor) values ('PDA', 'Puddephatt');
insert into subject (name, tutor) values ('OLTP', 'Warbey');
insert into subject (name, tutor) values ('CD Mastering', 'Van''t Hoff');
insert into subject (name, tutor) values ('Automation', 'Skaife d''Ingerthorpe');
insert into subject (name, tutor) values ('Classroom', 'Goch');
insert into subject (name, tutor) values ('Broadcast Journalism', 'Nottingham');
insert into subject (name, tutor) values ('Sleep Apnea', 'Toulson');
insert into subject (name, tutor) values ('UNIX Utilities', 'Jennins');
insert into subject (name, tutor) values ('Video over IP', 'Cracknall');
insert into subject (name, tutor) values ('Functional Testing', 'Fettis');
insert into subject (name, tutor) values ('FDR', 'Balk');
insert into subject (name, tutor) values ('VRML', 'Stear');
insert into subject (name, tutor) values ('Rock Music', 'Maughan');
insert into subject (name, tutor) values ('osCommerce', 'McElvine');
insert into subject (name, tutor) values ('Sales Operations', 'Feehely');
insert into subject (name, tutor) values ('LUSAS', 'Jedrysik');
insert into subject (name, tutor) values ('PY', 'Tabor');
insert into subject (name, tutor) values ('Flex', 'Trinke');
insert into subject (name, tutor) values ('JRockit', 'Cullen');
insert into subject (name, tutor) values ('GDI+', 'Redrup');
insert into subject (name, tutor) values ('LPI', 'Cleeves');
insert into subject (name, tutor) values ('cGMP manufacturing', 'Skirvin');
insert into subject (name, tutor) values ('Pianist', 'Eastby');
insert into subject (name, tutor) values ('Market Risk', 'Challoner');
insert into subject (name, tutor) values ('Product Marketing', 'Hebbes');
insert into subject (name, tutor) values ('Media Relations', 'Ethington');
insert into subject (name, tutor) values ('Hypnosis', 'Adan');
insert into subject (name, tutor) values ('NLTK', 'Bumford');
insert into subject (name, tutor) values ('ODBC', 'Gaughan');
insert into subject (name, tutor) values ('CAD', 'Jikylls');
insert into subject (name, tutor) values ('SSL Certificates', 'Driussi');
insert into subject (name, tutor) values ('MKS', 'Le Provost');
insert into subject (name, tutor) values ('Durable Goods', 'Mant');
insert into subject (name, tutor) values ('SQL DB2', 'Ingarfield');
insert into subject (name, tutor) values ('Claim', 'Shurlock');
insert into subject (name, tutor) values ('PVElite', 'Purver');
insert into subject (name, tutor) values ('Hazard Analysis', 'Brummell');
insert into subject (name, tutor) values ('Analytical Ultracentrifugation', 'Gozzard');
insert into subject (name, tutor) values ('AXE', 'Tuke');
insert into subject (name, tutor) values ('XLSTAT', 'Marchington');
insert into subject (name, tutor) values ('GNU tools', 'Tytler');
insert into subject (name, tutor) values ('Epi Info', 'Josephov');
insert into subject (name, tutor) values ('Servers', 'Struis');
insert into subject (name, tutor) values ('Outerwear', 'Cella');
insert into subject (name, tutor) values ('JSON-RPC', 'Snalom');
insert into subject (name, tutor) values ('Agronomy', 'Jarad');
insert into subject (name, tutor) values ('CFD', 'Hullett');
insert into subject (name, tutor) values ('Pre-owned', 'Mendez');
insert into subject (name, tutor) values ('Engineering Management', 'Milstead');
insert into subject (name, tutor) values ('HP Networking', 'Speirs');
insert into subject (name, tutor) values ('Know-how', 'Mitkov');
insert into subject (name, tutor) values ('Urban Search &amp; Rescue', 'Zarfati');
insert into subject (name, tutor) values ('MQSI', 'Culp');
insert into subject (name, tutor) values ('Shopping Centers', 'Jobling');
insert into subject (name, tutor) values ('IT Solutions', 'Elby');
insert into subject (name, tutor) values ('Oracle HR', 'Vanshin');
insert into subject (name, tutor) values ('FME', 'Jakucewicz');
insert into subject (name, tutor) values ('DST', 'Brede');
insert into subject (name, tutor) values ('Play-by-play', 'Cobbled');
insert into subject (name, tutor) values ('pfSense', 'Bakster');
insert into subject (name, tutor) values ('Kayak', 'Cuffley');
insert into subject (name, tutor) values ('BMC Remedy Administration', 'Coyish');
insert into subject (name, tutor) values ('RSA Security', 'Chedgey');
insert into subject (name, tutor) values ('SGSN', 'Fipp');
insert into subject (name, tutor) values ('Lua', 'Mulholland');
insert into subject (name, tutor) values ('CSM', 'Lochran');
insert into subject (name, tutor) values ('TMA', 'Cowdray');
insert into subject (name, tutor) values ('Music Festivals', 'Cardoe');
insert into subject (name, tutor) values ('ZeroMQ', 'Soots');
insert into subject (name, tutor) values ('Swift', 'Goult');
insert into subject (name, tutor) values ('Investment Banking', 'Cruikshanks');
insert into subject (name, tutor) values ('Oil Painting', 'Stepto');
insert into subject (name, tutor) values ('RTL Design', 'Truelove');
insert into subject (name, tutor) values ('High Yield', 'Rillatt');
insert into subject (name, tutor) values ('Experimentation', 'Hazeldene');
insert into subject (name, tutor) values ('Functional Training', 'Pitkeathley');
insert into subject (name, tutor) values ('English', 'Jaksic');
insert into subject (name, tutor) values ('OEM negotiations', 'Ommanney');
insert into subject (name, tutor) values ('Zinc', 'Attwill');
insert into subject (name, tutor) values ('DSL', 'Lilleycrop');
insert into subject (name, tutor) values ('Keyboards', 'Birkby');
insert into subject (name, tutor) values ('Crystal Reports', 'Treven');
insert into subject (name, tutor) values ('Crystal Xcelsius 2008', 'Warr');
insert into subject (name, tutor) values ('Dutch', 'Gratten');
insert into subject (name, tutor) values ('Arbitration', 'Hindrick');
insert into subject (name, tutor) values ('Image Editing', 'Blatchford');
insert into subject (name, tutor) values ('Sales Tax', 'Lathbury');
insert into subject (name, tutor) values ('Professional Services', 'Smeall');
insert into subject (name, tutor) values ('Kohana Framework', 'Gregorin');
insert into subject (name, tutor) values ('Investments', 'Blunsom');
insert into subject (name, tutor) values ('Political Economy', 'Buney');
insert into subject (name, tutor) values ('Omega', 'Launder');
insert into subject (name, tutor) values ('Software Implementation', 'Alban');
insert into subject (name, tutor) values ('European Union', 'Chellenham');
insert into subject (name, tutor) values ('FDS', 'Spiring');
insert into subject (name, tutor) values ('International Political Economy', 'Grigaut');
insert into subject (name, tutor) values ('Sun One LDAP', 'Whitticks');
insert into subject (name, tutor) values ('DSE Assessments', 'Ioannou');
insert into subject (name, tutor) values ('Internet Yellow Pages', 'Gilligan');
insert into subject (name, tutor) values ('LPC', 'Hawthorne');
insert into subject (name, tutor) values ('Risk Analysis', 'Soares');
insert into subject (name, tutor) values ('DFX', 'Matityahu');
insert into subject (name, tutor) values ('Sound', 'Kinig');
insert into subject (name, tutor) values ('ERP', 'Blinkhorn');
insert into subject (name, tutor) values ('RSVP-TE', 'Sainsbury');
insert into subject (name, tutor) values ('FDCPA', 'Burgane');
insert into subject (name, tutor) values ('Zemax', 'Ablott');
insert into subject (name, tutor) values ('IOT', 'Woodvine');
insert into subject (name, tutor) values ('KPI Dashboards', 'Sproul');
insert into subject (name, tutor) values ('RPT', 'Kirman');
insert into subject (name, tutor) values ('AFM', 'Doumerc');
insert into subject (name, tutor) values ('AVEVA PDMS', 'Cotty');
insert into subject (name, tutor) values ('Keyshot', 'Macauley');
insert into subject (name, tutor) values ('OCLC Connexion', 'Richmond');
insert into subject (name, tutor) values ('DVD Authoring', 'Kienlein');
insert into subject (name, tutor) values ('OGC', 'Whinray');
insert into subject (name, tutor) values ('Vehicles', 'Laidlow');
insert into subject (name, tutor) values ('DCN', 'McCaughren');
insert into subject (name, tutor) values ('DxDesigner', 'Pallesen');
insert into subject (name, tutor) values ('Medical Terminology', 'Braidley');
insert into subject (name, tutor) values ('MBTI', 'Martygin');
insert into subject (name, tutor) values ('Venipuncture', 'Southey');
insert into subject (name, tutor) values ('Customer Service', 'Camber');
insert into subject (name, tutor) values ('IT Outsourcing', 'Tickle');
insert into subject (name, tutor) values ('TSS', 'Fenkel');
insert into subject (name, tutor) values ('EOR', 'Everil');
insert into subject (name, tutor) values ('VXI', 'Lunt');
insert into subject (name, tutor) values ('Forecasting', 'Simpkin');
insert into subject (name, tutor) values ('Youth At Risk', 'Mattisson');
insert into subject (name, tutor) values ('Avaya Communication Manager', 'Beaver');
insert into subject (name, tutor) values ('MCEV', 'Renachowski');
insert into subject (name, tutor) values ('Twisted', 'Mapplethorpe');
insert into subject (name, tutor) values ('Customer Support', 'Casperri');
insert into subject (name, tutor) values ('OS/400', 'Longwood');
insert into subject (name, tutor) values ('Offshoring', 'Berggren');
insert into subject (name, tutor) values ('Epistemology', 'Clues');
insert into subject (name, tutor) values ('Tcl-Tk', 'Feldmesser');
insert into subject (name, tutor) values ('NPDES', 'Anderton');
insert into subject (name, tutor) values ('Civil Litigation', 'Burcombe');
insert into subject (name, tutor) values ('ENOVIA LCA', 'Ovitts');
insert into subject (name, tutor) values ('HR Information Management', 'Crossthwaite');
insert into subject (name, tutor) values ('Electrical Controls', 'Manford');
insert into subject (name, tutor) values ('TMMi', 'Bland');
insert into subject (name, tutor) values ('Embedded Systems', 'Bullingham');
insert into subject (name, tutor) values ('VMware Server', 'MacNeish');
insert into subject (name, tutor) values ('SMS', 'Francescuzzi');
insert into subject (name, tutor) values ('European Computer Driving Licence', 'Grishakov');
insert into subject (name, tutor) values ('HTC', 'Bolino');
insert into subject (name, tutor) values ('Kinesio Taping', 'Tilbrook');
insert into subject (name, tutor) values ('iOS Development', 'Argue');
insert into subject (name, tutor) values ('IPSec', 'Thorsen');
insert into subject (name, tutor) values ('HSP', 'Lathleiff');
insert into subject (name, tutor) values ('PML', 'Weedall');
insert into subject (name, tutor) values ('BTS', 'Shoesmith');
insert into subject (name, tutor) values ('DNA methylation', 'Fessler');
insert into subject (name, tutor) values ('Manufacturing Operations Management', 'Fould');
insert into subject (name, tutor) values ('PMIS', 'Paulo');
insert into subject (name, tutor) values ('RPG II', 'Audenis');
insert into subject (name, tutor) values ('ICH Guidelines', 'Rodder');
insert into subject (name, tutor) values ('DFT Compiler', 'Eitter');
insert into subject (name, tutor) values ('Nuclear', 'Dorgan');
insert into subject (name, tutor) values ('Glass', 'Furnell');
insert into subject (name, tutor) values ('CME', 'Ovise');
insert into subject (name, tutor) values ('UMA', 'Stanley');
insert into subject (name, tutor) values ('Medical Affairs', 'Gorger');
insert into subject (name, tutor) values ('Natural Resources', 'Huertas');
insert into subject (name, tutor) values ('Trials', 'Picford');
insert into subject (name, tutor) values ('Tax Accounting', 'Keher');
insert into subject (name, tutor) values ('BPML', 'Akess');
insert into subject (name, tutor) values ('Low Voltage', 'Weeds');
insert into subject (name, tutor) values ('Escrow', 'Cradey');
insert into subject (name, tutor) values ('VMI Programs', 'Itzkovwich');
insert into subject (name, tutor) values ('OID', 'Layburn');
insert into subject (name, tutor) values ('Jet Engines', 'VanBrugh');
insert into subject (name, tutor) values ('Axys', 'Zipsell');
insert into subject (name, tutor) values ('TMDLs', 'Olivas');
insert into subject (name, tutor) values ('UAV', 'Wison');
insert into subject (name, tutor) values ('DVD', 'O''Brogane');
insert into subject (name, tutor) values ('Songwriting', 'Carless');
insert into subject (name, tutor) values ('Dbx', 'Lias');
insert into subject (name, tutor) values ('Youth Empowerment', 'Cordobes');
insert into subject (name, tutor) values ('Ultrasound Therapy', 'Slowey');
insert into subject (name, tutor) values ('Medical Billing', 'Hadden');
insert into subject (name, tutor) values ('Operating Room', 'Belchamp');
insert into subject (name, tutor) values ('Operational Oversight', 'Pettifer');
insert into subject (name, tutor) values ('NATO', 'Derrell');
insert into subject (name, tutor) values ('Fashion', 'Nardoni');
insert into subject (name, tutor) values ('MC2', 'Samsonsen');
insert into subject (name, tutor) values ('Cerner CCL', 'Lodeke');
insert into subject (name, tutor) values ('Global Sourcing', 'Edden');
insert into subject (name, tutor) values ('Eyebrow', 'Burdus');
insert into subject (name, tutor) values ('Lua', 'Penhall');
insert into subject (name, tutor) values ('AWS CWI', 'Cussen');
insert into subject (name, tutor) values ('Bartending', 'Armitt');
insert into subject (name, tutor) values ('Software Engineering', 'Gretton');
insert into subject (name, tutor) values ('Early Childhood Development', 'Benbrick');
insert into subject (name, tutor) values ('iSCSI', 'Renzo');
insert into subject (name, tutor) values ('Business Analysis', 'Salla');
insert into subject (name, tutor) values ('Job Fairs', 'Warlawe');
insert into subject (name, tutor) values ('Air Quality', 'Eringey');
insert into subject (name, tutor) values ('Vehicle Dynamics', 'Kail');
insert into subject (name, tutor) values ('Microsoft Excel', 'Osbidston');
insert into subject (name, tutor) values ('GUI', 'Cawston');
insert into subject (name, tutor) values ('Critical Care', 'Vosse');
insert into subject (name, tutor) values ('Norton Utilities', 'Hebden');
insert into subject (name, tutor) values ('NCS', 'Scarborough');
insert into subject (name, tutor) values ('Film Production', 'Mollindinia');
insert into subject (name, tutor) values ('LLVM', 'Thaxton');
insert into subject (name, tutor) values ('Hodes IQ', 'Birrell');
insert into subject (name, tutor) values ('Jive', 'Ringwood');
insert into subject (name, tutor) values ('Substance Use Disorders', 'Robottom');
insert into subject (name, tutor) values ('Hybrid Cloud', 'Fierro');
insert into subject (name, tutor) values ('XAMPP', 'Hurich');
insert into subject (name, tutor) values ('AC Nielsen', 'Slimings');
insert into subject (name, tutor) values ('UFS', 'Hastwell');
insert into subject (name, tutor) values ('TWIC Card', 'Abbey');
insert into subject (name, tutor) values ('Clerical Skills', 'Shorland');
insert into subject (name, tutor) values ('Corporate Governance', 'Budnik');
insert into subject (name, tutor) values ('Pricing', 'Caddell');
insert into subject (name, tutor) values ('Financial Mgmt', 'Bullman');
insert into subject (name, tutor) values ('DDMS', 'Wileman');
insert into subject (name, tutor) values ('Internet TV', 'McLagan');
insert into subject (name, tutor) values ('Oil &amp; Gas Exploration', 'Densun');
insert into subject (name, tutor) values ('Payroll Taxes', 'Strank');
insert into subject (name, tutor) values ('Eze Castle', 'Dillamore');
insert into subject (name, tutor) values ('LPCVD', 'Nussen');
insert into subject (name, tutor) values ('Consumer Behaviour', 'Healy');
insert into subject (name, tutor) values ('GMC PrintNet T', 'Milam');
insert into subject (name, tutor) values ('FW', 'Geard');
insert into subject (name, tutor) values ('Culinary Skills', 'Pawnsford');
insert into subject (name, tutor) values ('GPS Units', 'Bastie');
insert into subject (name, tutor) values ('Xsigo', 'Collyear');
insert into subject (name, tutor) values ('Rail', 'Carhart');
insert into subject (name, tutor) values ('TKI', 'Salman');
insert into subject (name, tutor) values ('CSV', 'Ruseworth');
insert into subject (name, tutor) values ('LEED AP', 'Skillitt');
insert into subject (name, tutor) values ('Avaya Technologies', 'Lowey');
insert into subject (name, tutor) values ('Xenix', 'Shave');
insert into subject (name, tutor) values ('uC/OS-II', 'Breckon');
insert into subject (name, tutor) values ('Solvency II', 'Humburton');
insert into subject (name, tutor) values ('Icon Design', 'Jeannenet');
insert into subject (name, tutor) values ('SMT Kingdom', 'Bartaloni');
insert into subject (name, tutor) values ('Governmental Affairs', 'Hainey');
insert into subject (name, tutor) values ('World War II', 'Keddey');
insert into subject (name, tutor) values ('FSC Certification', 'Linskill');
insert into subject (name, tutor) values ('Newspapers', 'Buzza');
insert into subject (name, tutor) values ('Art Direction', 'Gut');
insert into subject (name, tutor) values ('RMADS', 'Ben-Aharon');
insert into subject (name, tutor) values ('Air Quality', 'Laetham');
insert into subject (name, tutor) values ('Virtual PC', 'Gregoratti');
insert into subject (name, tutor) values ('International Tax', 'Orrocks');
insert into subject (name, tutor) values ('New Media', 'Pressland');
insert into subject (name, tutor) values ('Yield Management', 'Tzuker');
insert into subject (name, tutor) values ('CFDesign', 'Marvelley');
insert into subject (name, tutor) values ('Operating Systems', 'Kohrsen');
insert into subject (name, tutor) values ('New Media', 'Nestoruk');
insert into subject (name, tutor) values ('Drywall', 'Ballston');
insert into subject (name, tutor) values ('FX Animation', 'Bloan');
insert into subject (name, tutor) values ('Google Webmaster Tools', 'Rogan');
insert into subject (name, tutor) values ('Online Gambling', 'Beagin');
insert into subject (name, tutor) values ('Exercise Physiology', 'Jenton');
insert into subject (name, tutor) values ('LDOM', 'Wiersma');
insert into subject (name, tutor) values ('ICH-GCP', 'MacPeice');
insert into subject (name, tutor) values ('Target Costing', 'Belle');
insert into subject (name, tutor) values ('AutoCAD', 'Robertsson');
insert into subject (name, tutor) values ('Ultrasound Therapy', 'Huc');
insert into subject (name, tutor) values ('CCIP', 'Schuck');
insert into subject (name, tutor) values ('AP Style', 'St. Leger');
insert into subject (name, tutor) values ('Operational Oversight', 'Hurburt');
insert into subject (name, tutor) values ('PSpice', 'Lavelle');
insert into subject (name, tutor) values ('Xbox 360', 'Spencook');
insert into subject (name, tutor) values ('MbUnit', 'Enbury');
insert into subject (name, tutor) values ('DNS Server', 'Lindenfeld');
insert into subject (name, tutor) values ('OS/390', 'Fontanet');
insert into subject (name, tutor) values ('Xsan', 'O''Heffernan');
insert into subject (name, tutor) values ('ETFs', 'Hakonsson');
insert into subject (name, tutor) values ('MYOB', 'Hauger');
insert into subject (name, tutor) values ('Nintendo DS', 'Fernez');
insert into subject (name, tutor) values ('CICS', 'Lodevick');
insert into subject (name, tutor) values ('Sustainable Agriculture', 'Privost');
insert into subject (name, tutor) values ('Phase II Environmental Site Assessments', 'Harriott');
insert into subject (name, tutor) values ('Petrochemical', 'Reckus');
insert into subject (name, tutor) values ('CMA', 'Wyley');
insert into subject (name, tutor) values ('Ministry Of Defence', 'MacKnockiter');
insert into subject (name, tutor) values ('Avaya AES', 'Spowage');
insert into subject (name, tutor) values ('Statistics', 'Ledwidge');
insert into subject (name, tutor) values ('CQS', 'Hassey');
insert into subject (name, tutor) values ('HCAHPS', 'Gemmill');
insert into subject (name, tutor) values ('Zyxel', 'Pantling');
insert into subject (name, tutor) values ('Hedge Funds', 'Nuss');
insert into subject (name, tutor) values ('FMV', 'Durston');
insert into subject (name, tutor) values ('Working Abroad', 'Douthwaite');
insert into subject (name, tutor) values ('DBVisualizer', 'Mault');
insert into subject (name, tutor) values ('z/OS', 'Joint');
insert into subject (name, tutor) values ('Options', 'Lyburn');
insert into subject (name, tutor) values ('Drafting Agreements', 'Sarginson');
insert into subject (name, tutor) values ('PTO', 'Blofeld');
insert into subject (name, tutor) values ('Microsoft MVP', 'Virgoe');
insert into subject (name, tutor) values ('UK Tax', 'Purchon');
insert into subject (name, tutor) values ('Fertility', 'Greader');
insert into subject (name, tutor) values ('Event Management', 'Fleay');
insert into subject (name, tutor) values ('Allergy', 'Cheater');
insert into subject (name, tutor) values ('Major Gift Development', 'Shropshire');
insert into subject (name, tutor) values ('Hotel Management', 'Brassill');
insert into subject (name, tutor) values ('Atmel AVR', 'Hanlin');
insert into subject (name, tutor) values ('Fund Accounting', 'Dumper');
insert into subject (name, tutor) values ('ADP Payroll', 'Houldin');
insert into subject (name, tutor) values ('Brand Management', 'Valasek');
insert into subject (name, tutor) values ('PPV', 'Godden');
insert into subject (name, tutor) values ('Corporate Governance', 'Praton');
insert into subject (name, tutor) values ('Zuken', 'Meert');
insert into subject (name, tutor) values ('Light Rail', 'Paddick');
insert into subject (name, tutor) values ('FDT', 'Wiburn');
insert into subject (name, tutor) values ('Modeling', 'Von Brook');
insert into subject (name, tutor) values ('Site Plans', 'Georgeot');
insert into subject (name, tutor) values ('RMI', 'Scamadin');
insert into subject (name, tutor) values ('Quality Patient Care', 'Cund');
insert into subject (name, tutor) values ('Business Intelligence', 'Duffyn');
insert into subject (name, tutor) values ('CXF', 'Cotton');
insert into subject (name, tutor) values ('Cross-border Transactions', 'Dowrey');
insert into subject (name, tutor) values ('MBR', 'Pinckard');
insert into subject (name, tutor) values ('Customer Acquisition', 'Belsey');
insert into subject (name, tutor) values ('DCOM', 'Cavnor');
insert into subject (name, tutor) values ('TMS320', 'Rojel');
insert into subject (name, tutor) values ('RIP', 'Usborn');
insert into subject (name, tutor) values ('Glasses', 'Buessen');
insert into subject (name, tutor) values ('LN', 'Beckmann');
insert into subject (name, tutor) values ('International Human Rights', 'Coat');
insert into subject (name, tutor) values ('Xilinx', 'Klausewitz');
insert into subject (name, tutor) values ('Illustrator', 'Dallas');
insert into subject (name, tutor) values ('VCL', 'Faircliff');
insert into subject (name, tutor) values ('IPSec', 'LaBastida');
insert into subject (name, tutor) values ('Kronos WFC', 'McLenahan');
insert into subject (name, tutor) values ('Airport Management', 'Snaith');
insert into subject (name, tutor) values ('OTDR', 'Quinlan');
insert into subject (name, tutor) values ('Working Capital Management', 'Heiden');
insert into subject (name, tutor) values ('Umbrellas', 'Tal');
insert into subject (name, tutor) values ('Job Costing', 'Lydiate');
insert into subject (name, tutor) values ('Rehabilitation Psychology', 'Dewan');
insert into subject (name, tutor) values ('Olympic Lifting', 'Gariff');
insert into subject (name, tutor) values ('Construction Safety', 'Penk');
insert into subject (name, tutor) values ('Web TV', 'Cowles');
insert into subject (name, tutor) values ('DX200', 'Ovenell');
insert into subject (name, tutor) values ('Urban Search &amp; Rescue', 'Nias');
insert into subject (name, tutor) values ('Oversight', 'Gomm');
insert into subject (name, tutor) values ('JBoss ESB', 'Cholerton');
insert into subject (name, tutor) values ('JBoss Seam', 'Feldberger');
insert into subject (name, tutor) values ('Ntop', 'Grancher');
insert into subject (name, tutor) values ('ZBrush', 'Mockford');
insert into subject (name, tutor) values ('Zillow', 'Biesterfeld');
insert into subject (name, tutor) values ('Pipefitting', 'McBrearty');
insert into subject (name, tutor) values ('Data Integration', 'Swenson');
insert into subject (name, tutor) values ('BGAN', 'Hark');
insert into subject (name, tutor) values ('Military Affairs', 'Rillett');
insert into subject (name, tutor) values ('Prenuptial Agreements', 'Kirkland');
insert into subject (name, tutor) values ('eGain', 'Stuchburie');
insert into subject (name, tutor) values ('Honeywell DCS', 'Lemarie');
insert into subject (name, tutor) values ('WS', 'Asquith');
insert into subject (name, tutor) values ('Microsoft Dynamics GP', 'Attoe');
insert into subject (name, tutor) values ('FEM analysis', 'Klaves');
insert into subject (name, tutor) values ('Geography', 'Glasheen');
insert into subject (name, tutor) values ('Hospitality Management', 'Pirot');
insert into subject (name, tutor) values ('RTI', 'Frowde');
insert into subject (name, tutor) values ('Demand Generation', 'Balk');
insert into subject (name, tutor) values ('Owner-managed businesses', 'Fulstow');
insert into subject (name, tutor) values ('LVDS', 'Daville');
insert into subject (name, tutor) values ('Oil Painting', 'Finnan');
insert into subject (name, tutor) values ('eEye Retina', 'Orrey');
insert into subject (name, tutor) values ('Mineral Exploration', 'Beresfore');
insert into subject (name, tutor) values ('RLM', 'Docket');
insert into subject (name, tutor) values ('Hatha Yoga', 'Thornley');
insert into subject (name, tutor) values ('Culinary Skills', 'Langthorn');
insert into subject (name, tutor) values ('Lutron', 'Rottery');
insert into subject (name, tutor) values ('Axure RP', 'Isoldi');
insert into subject (name, tutor) values ('WPF', 'Poulston');
insert into subject (name, tutor) values ('Red Hat Linux', 'Oulet');
insert into subject (name, tutor) values ('Icon Design', 'Sked');
insert into subject (name, tutor) values ('QINSy', 'Pedler');
insert into subject (name, tutor) values ('QSI', 'Hellyar');
insert into subject (name, tutor) values ('Ehcache', 'Duddy');
insert into subject (name, tutor) values ('TDMA', 'Marrable');
insert into subject (name, tutor) values ('Turkish', 'Birdseye');
insert into subject (name, tutor) values ('DLC', 'Tunnadine');
insert into subject (name, tutor) values ('French', 'Gillam');
insert into subject (name, tutor) values ('LRO', 'Conningham');
insert into subject (name, tutor) values ('Distribution Center Operations', 'Rushby');
insert into subject (name, tutor) values ('FWSM', 'Walch');
insert into subject (name, tutor) values ('NS-2', 'Petriello');
insert into subject (name, tutor) values ('Pharmaceutical Sales', 'Flatt');
insert into subject (name, tutor) values ('Owner Representation', 'Larkcum');
insert into subject (name, tutor) values ('Windows Server', 'Gutman');
insert into subject (name, tutor) values ('Cultural Awareness', 'Wiseman');
insert into subject (name, tutor) values ('Hospitals', 'Tunney');
insert into subject (name, tutor) values ('Government Contracting', 'Rego');
insert into subject (name, tutor) values ('Early Childhood Development', 'Georgius');
insert into subject (name, tutor) values ('Ocean Freight', 'Borham');
insert into subject (name, tutor) values ('CentOS', 'Mauger');
insert into subject (name, tutor) values ('SolidWorks', 'Bramham');
insert into subject (name, tutor) values ('Hotel Booking', 'Moon');
insert into subject (name, tutor) values ('HSQE', 'Fassan');
insert into subject (name, tutor) values ('Yelp', 'Ilyenko');
insert into subject (name, tutor) values ('Upstream', 'Robertis');
insert into subject (name, tutor) values ('eEye Retina', 'Inworth');
insert into subject (name, tutor) values ('CSI', 'Snelman');
insert into subject (name, tutor) values ('Portuguese', 'Tattersdill');
insert into subject (name, tutor) values ('XCOM', 'Gellion');
insert into subject (name, tutor) values ('SAP MDM', 'Earles');
insert into subject (name, tutor) values ('EAI', 'Kittle');
insert into subject (name, tutor) values ('FTP', 'Gifkins');
insert into subject (name, tutor) values ('Oil Analysis', 'Rhead');
insert into subject (name, tutor) values ('WUFI', 'Brunsden');
insert into subject (name, tutor) values ('Value Engineering', 'Danels');
insert into subject (name, tutor) values ('Driven By Results', 'Crisell');
insert into subject (name, tutor) values ('RFP', 'Bloodworthe');
insert into subject (name, tutor) values ('Commercial Lending', 'Laffling');
insert into subject (name, tutor) values ('LDOM', 'Fealy');
insert into subject (name, tutor) values ('RCSA', 'Pinkett');
insert into subject (name, tutor) values ('Global Management', 'Leggott');
insert into subject (name, tutor) values ('Immigration Law', 'Curphey');
insert into subject (name, tutor) values ('HDX', 'Yo');
insert into subject (name, tutor) values ('Social Psychology', 'Sollett');
insert into subject (name, tutor) values ('Youth Mentoring', 'Gainforth');
insert into subject (name, tutor) values ('ICT', 'Foyle');
insert into subject (name, tutor) values ('RCSA', 'Raubenheimer');
insert into subject (name, tutor) values ('Unit Testing', 'Spacie');
insert into subject (name, tutor) values ('TDR', 'Parkisson');
insert into subject (name, tutor) values ('CTQ', 'Scotfurth');
insert into subject (name, tutor) values ('ArcGIS', 'Moller');
insert into subject (name, tutor) values ('QML', 'Pitkin');
insert into subject (name, tutor) values ('RV', 'Dominighi');
insert into subject (name, tutor) values ('Job Evaluation', 'Cowton');
insert into subject (name, tutor) values ('MRIS', 'Savine');
insert into subject (name, tutor) values ('SCADA', 'Witherbed');
insert into subject (name, tutor) values ('LCR', 'Shemmans');
insert into subject (name, tutor) values ('IBC', 'Affleck');
insert into subject (name, tutor) values ('Jazz', 'Bellenie');
insert into subject (name, tutor) values ('Microsoft MVP', 'Konmann');
insert into subject (name, tutor) values ('GFAS', 'Adess');
insert into subject (name, tutor) values ('Business Intelligence Tools', 'Fasset');
insert into subject (name, tutor) values ('Franchising', 'Thomson');
insert into subject (name, tutor) values ('TBB', 'Sedgemond');
insert into subject (name, tutor) values ('Umbraco', 'Pauluzzi');
insert into subject (name, tutor) values ('Bloomberg', 'Derrington');
insert into subject (name, tutor) values ('Smart Cards', 'Laughlan');
insert into subject (name, tutor) values ('Demand Generation', 'Pfertner');
insert into subject (name, tutor) values ('Eye Tracking', 'Petera');
insert into subject (name, tutor) values ('Routing Protocols', 'Greenly');
insert into subject (name, tutor) values ('IFTA', 'Koba');
insert into subject (name, tutor) values ('Video Games', 'Melson');
insert into subject (name, tutor) values ('Ticketing', 'Linkin');
insert into subject (name, tutor) values ('DS4000', 'Pocklington');
insert into subject (name, tutor) values ('XML Schema Design', 'Greening');
insert into subject (name, tutor) values ('Observation', 'Klees');
insert into subject (name, tutor) values ('FBCB2', 'Chantillon');
insert into subject (name, tutor) values ('Six Sigma', 'Powles');
insert into subject (name, tutor) values ('Outside Sales', 'Bufton');
insert into subject (name, tutor) values ('Spreadsheets', 'McLise');
insert into subject (name, tutor) values ('TPX', 'Load');
insert into subject (name, tutor) values ('Psychopharmacology', 'Di Francecshi');
insert into subject (name, tutor) values ('Krav Maga', 'Puckring');
insert into subject (name, tutor) values ('PDMS Draft', 'Lilbourne');
insert into subject (name, tutor) values ('Umbrellas', 'Hammersley');
insert into subject (name, tutor) values ('Design Patterns', 'Trayford');
insert into subject (name, tutor) values ('JSON', 'Clemow');
insert into subject (name, tutor) values ('FF&amp;E Specifications', 'Moulds');
insert into subject (name, tutor) values ('Defect Life Cycle', 'Laird');
insert into subject (name, tutor) values ('Aesthetics', 'Colbeck');
insert into subject (name, tutor) values ('Trading Systems', 'Fright');
insert into subject (name, tutor) values ('OLTP', 'Lorrie');
insert into subject (name, tutor) values ('Embedded Systems', 'Nani');
insert into subject (name, tutor) values ('Gnuplot', 'James');
insert into subject (name, tutor) values ('US Tax', 'Stanman');
insert into subject (name, tutor) values ('UTP', 'Yakhin');
insert into subject (name, tutor) values ('Web Typography', 'Olding');
insert into subject (name, tutor) values ('PFMEA', 'Guillford');
insert into subject (name, tutor) values ('Health Education', 'Laphorn');
insert into subject (name, tutor) values ('Physical Therapy', 'Tegeller');
insert into subject (name, tutor) values ('Claims Management', 'Marchington');
insert into subject (name, tutor) values ('EOB', 'Treversh');
insert into subject (name, tutor) values ('Jewelry', 'Rahlof');
insert into subject (name, tutor) values ('Statistics', 'Treadger');
insert into subject (name, tutor) values ('DVB-C', 'Gavozzi');
insert into subject (name, tutor) values ('Xdebug', 'Kloster');
insert into subject (name, tutor) values ('PDP', 'McGilleghole');
insert into subject (name, tutor) values ('Interpersonal Skills', 'Hassan');
insert into subject (name, tutor) values ('Dbx', 'Blackledge');
insert into subject (name, tutor) values ('First Time Home Sellers', 'Keysall');
insert into subject (name, tutor) values ('Fine Dining', 'Lettley');
insert into subject (name, tutor) values ('HMI Configuration', 'Shakelade');
insert into subject (name, tutor) values ('TTL', 'McGettrick');
insert into subject (name, tutor) values ('World War II', 'Bevington');
insert into subject (name, tutor) values ('RRSP', 'Beaumont');
insert into subject (name, tutor) values ('QinQ', 'Larwell');
insert into subject (name, tutor) values ('NCSim', 'Gilford');
insert into subject (name, tutor) values ('McKesson PACS', 'Sandwith');
insert into subject (name, tutor) values ('Relationship Building', 'Blodget');
insert into subject (name, tutor) values ('Airport Management', 'Stuckow');
insert into subject (name, tutor) values ('Dtrace', 'Crampton');
insert into subject (name, tutor) values ('TMJ Dysfunction', 'MacPaike');
insert into subject (name, tutor) values ('SQF', 'MacGowan');
insert into subject (name, tutor) values ('SLES', 'Crucitti');
insert into subject (name, tutor) values ('Content Strategy', 'Chattaway');
insert into subject (name, tutor) values ('SAP Business ByDesign', 'Swadlinge');
insert into subject (name, tutor) values ('CSA 2010', 'Ashness');
insert into subject (name, tutor) values ('Database Design', 'Doyle');
insert into subject (name, tutor) values ('Music', 'Menghi');
insert into subject (name, tutor) values ('OnQ', 'Twinborne');
insert into subject (name, tutor) values ('Golf', 'Cristofori');
insert into subject (name, tutor) values ('CNG', 'Nevison');
insert into subject (name, tutor) values ('SFE', 'Medling');
insert into subject (name, tutor) values ('XaaS', 'Wilmut');
insert into subject (name, tutor) values ('Network Design', 'Hawford');
insert into subject (name, tutor) values ('Ulcerative Colitis', 'Esgate');
insert into subject (name, tutor) values ('Observational Astronomy', 'Juszczak');
insert into subject (name, tutor) values ('BTS Installation', 'Langlois');
insert into subject (name, tutor) values ('ATP', 'Metterick');
insert into subject (name, tutor) values ('JavaScript Libraries', 'Sandcroft');
insert into subject (name, tutor) values ('Ffmpeg', 'Broome');
insert into subject (name, tutor) values ('Biotechnology', 'Beeze');
insert into subject (name, tutor) values ('Pyrosequencing', 'Abraham');
insert into subject (name, tutor) values ('nDo', 'Bonelle');
insert into subject (name, tutor) values ('Group Policy', 'Crone');
insert into subject (name, tutor) values ('Year-end Close', 'Innot');
insert into subject (name, tutor) values ('Power Utilities', 'Aronstein');
insert into subject (name, tutor) values ('Canon XL2', 'Palethorpe');
insert into subject (name, tutor) values ('Framing', 'Jakoubek');
insert into subject (name, tutor) values ('Strategic Partnerships', 'Freckleton');
insert into subject (name, tutor) values ('QNX', 'O''Connolly');
insert into subject (name, tutor) values ('Web TV', 'Maggill''Andreis');
insert into subject (name, tutor) values ('NHPA', 'Rockliffe');
insert into subject (name, tutor) values ('Spanish', 'Calam');
insert into subject (name, tutor) values ('Pylons', 'Geeson');
insert into subject (name, tutor) values ('Medicare', 'Allnutt');
insert into subject (name, tutor) values ('Eblasts', 'Robke');
insert into subject (name, tutor) values ('AOD', 'Tibald');
insert into subject (name, tutor) values ('Thermal Oxidizers', 'Desmond');
insert into subject (name, tutor) values ('EU Funding', 'Grigoletti');
insert into subject (name, tutor) values ('Ductwork', 'Smolan');
insert into subject (name, tutor) values ('Illustrator', 'Pointin');
insert into subject (name, tutor) values ('Defect Life Cycle', 'De Luna');
insert into subject (name, tutor) values ('AMSI', 'Lammerding');
insert into subject (name, tutor) values ('Pre-owned', 'Arbon');
insert into subject (name, tutor) values ('Special Events', 'Partener');
insert into subject (name, tutor) values ('Mixed-use', 'Becke');
insert into subject (name, tutor) values ('HR Strategy', 'Salasar');
insert into subject (name, tutor) values ('ODBC', 'Seville');
insert into subject (name, tutor) values ('Thermal Oxidation', 'Ayerst');
insert into subject (name, tutor) values ('SAP', 'Mussett');
insert into subject (name, tutor) values ('Financial Services', 'Lythgoe');
insert into subject (name, tutor) values ('BtB', 'Labram');
insert into subject (name, tutor) values ('Mythology', 'Argo');
insert into subject (name, tutor) values ('Xcalibur', 'Hartegan');
insert into subject (name, tutor) values ('BMC Portal', 'McGrirl');
insert into subject (name, tutor) values ('Business Ethics', 'Kibard');
insert into subject (name, tutor) values ('Static Timing Analysis', 'Stockbridge');
insert into subject (name, tutor) values ('CD covers', 'Norcott');
insert into subject (name, tutor) values ('GTAW', 'Hannigan');
insert into subject (name, tutor) values ('TMX', 'Stitle');
insert into subject (name, tutor) values ('FDQM', 'O''Crowley');
insert into subject (name, tutor) values ('RCT', 'Eggers');
insert into subject (name, tutor) values ('Tween', 'Rozzell');
insert into subject (name, tutor) values ('CMOS', 'O'' Markey');
insert into subject (name, tutor) values ('Programming', 'Thake');
insert into subject (name, tutor) values ('RTF', 'Brymner');
insert into subject (name, tutor) values ('Oil &amp; Gas Exploration', 'Skelington');
insert into subject (name, tutor) values ('Employee Relations', 'Trotton');
insert into subject (name, tutor) values ('Python', 'Woofinden');
insert into subject (name, tutor) values ('DNA Repair', 'Doodney');
insert into subject (name, tutor) values ('Rhino 3D', 'Martyntsev');
insert into subject (name, tutor) values ('ASME', 'Flacknell');
insert into subject (name, tutor) values ('GSLC', 'Warrier');
insert into subject (name, tutor) values ('Biology', 'Godier');
insert into subject (name, tutor) values ('TCAP', 'Innocent');
insert into subject (name, tutor) values ('Smart Metering', 'Mackrell');
insert into subject (name, tutor) values ('Fire Alarm', 'Tweed');
insert into subject (name, tutor) values ('Online Lead Generation', 'Aloshechkin');
insert into subject (name, tutor) values ('UB04', 'Kinzel');
insert into subject (name, tutor) values ('Community Development', 'Mellers');
insert into subject (name, tutor) values ('Psychopharmacology', 'Hunnybun');
insert into subject (name, tutor) values ('Klarity', 'Gwyneth');
insert into subject (name, tutor) values ('Smartstream TLM', 'Creech');
insert into subject (name, tutor) values ('Ignite-UX', 'Purse');
insert into subject (name, tutor) values ('PMR', 'Winser');
insert into subject (name, tutor) values ('Omeka', 'Vannozzii');
insert into subject (name, tutor) values ('Data Warehousing', 'Hinze');
insert into subject (name, tutor) values ('World War II', 'Abramamov');
insert into subject (name, tutor) values ('Latin America', 'Flewitt');
insert into subject (name, tutor) values ('CDMA2000', 'Richings');
insert into subject (name, tutor) values ('PSD', 'Cockarill');
insert into subject (name, tutor) values ('Yacht Deliveries', 'Laughren');
insert into subject (name, tutor) values ('WLAN', 'Ellings');
insert into subject (name, tutor) values ('Pharmaceutics', 'Harome');
insert into subject (name, tutor) values ('Teaching Writing', 'Dyka');
insert into subject (name, tutor) values ('Valves', 'Sporrij');
insert into subject (name, tutor) values ('UNIX Utilities', 'Scotti');
insert into subject (name, tutor) values ('Equipment Installation', 'Johnson');
insert into subject (name, tutor) values ('SAP MM', 'Presnail');
insert into subject (name, tutor) values ('Sports Nutrition', 'Daglish');
insert into subject (name, tutor) values ('Citrix', 'Dartan');
insert into subject (name, tutor) values ('Acute Care', 'Boas');
insert into subject (name, tutor) values ('Linux System Administration', 'Roth');
insert into subject (name, tutor) values ('PMO Development', 'Hannigane');
insert into subject (name, tutor) values ('RSA Ace Server', 'Rayburn');
insert into subject (name, tutor) values ('Dutch', 'Daton');
insert into subject (name, tutor) values ('Genomics', 'Fendt');
insert into subject (name, tutor) values ('GC-MS', 'Denyakin');
insert into subject (name, tutor) values ('Airport Management', 'Zmitruk');
insert into subject (name, tutor) values ('Lean Manufacturing', 'Throssell');
insert into subject (name, tutor) values ('solid-state NMR', 'Claris');
insert into subject (name, tutor) values ('HDS', 'Brumfield');
insert into subject (name, tutor) values ('Fleet Management', 'Crook');
insert into subject (name, tutor) values ('NGL', 'Darke');
insert into subject (name, tutor) values ('QuarkXPress', 'Ranger');
insert into subject (name, tutor) values ('TVPaint', 'Dillicate');
insert into subject (name, tutor) values ('PTT', 'Ralls');
insert into subject (name, tutor) values ('Ultrasound Therapy', 'Boon');
insert into subject (name, tutor) values ('LAN Switching', 'Critten');
insert into subject (name, tutor) values ('ZeroMQ', 'Milsted');
insert into subject (name, tutor) values ('Rsync', 'Dumigan');
insert into subject (name, tutor) values ('SDTM', 'Kett');
insert into subject (name, tutor) values ('Vectorworks', 'Darco');
insert into subject (name, tutor) values ('Road', 'Ramey');
insert into subject (name, tutor) values ('NSI', 'Soar');
insert into subject (name, tutor) values ('Youth Marketing', 'MacAlpyne');
insert into subject (name, tutor) values ('EBA', 'Chiswell');
insert into subject (name, tutor) values ('Economic Policy', 'Shapter');
insert into subject (name, tutor) values ('Key Person Insurance', 'Lambe');
insert into subject (name, tutor) values ('DCL', 'Bomb');
insert into subject (name, tutor) values ('CPFR', 'Counter');
insert into subject (name, tutor) values ('QPSK', 'Snassell');
insert into subject (name, tutor) values ('SSBI', 'Burbury');
insert into subject (name, tutor) values ('NYS Notary Public', 'Oaks');
insert into subject (name, tutor) values ('BMC Remedy User', 'Clewley');
insert into subject (name, tutor) values ('IP Networking', 'Perrington');
insert into subject (name, tutor) values ('After FX', 'Loving');
insert into subject (name, tutor) values ('RHCE', 'Laffranconi');
insert into subject (name, tutor) values ('Executive Search', 'Leese');
insert into subject (name, tutor) values ('Oceanography', 'Leonarde');
insert into subject (name, tutor) values ('IEC 61850', 'Waldock');
insert into subject (name, tutor) values ('Navisworks', 'Gery');
insert into subject (name, tutor) values ('MVT', 'Bentame');
insert into subject (name, tutor) values ('Cost Efficiency', 'Gotecliffe');
insert into subject (name, tutor) values ('Ethernet', 'Sone');
insert into subject (name, tutor) values ('CDMA 1X', 'Powe');
insert into subject (name, tutor) values ('VDA', 'McKniely');
insert into subject (name, tutor) values ('People Skills', 'Gerlts');
insert into subject (name, tutor) values ('Change Management', 'Champain');
insert into subject (name, tutor) values ('Food Industry', 'Fery');
insert into subject (name, tutor) values ('Adobe Creative Suite', 'Turnbull');
insert into subject (name, tutor) values ('MVPN', 'Gheorghie');
insert into subject (name, tutor) values ('SRAM', 'Alexandrou');
insert into subject (name, tutor) values ('PMO Design', 'Gallagher');
insert into subject (name, tutor) values ('Menu Development', 'O''Shavlan');
insert into subject (name, tutor) values ('Erwin', 'Luter');
insert into subject (name, tutor) values ('Employee Management', 'Guillet');
insert into subject (name, tutor) values ('Nitric Oxide', 'Clements');
insert into subject (name, tutor) values ('WTP', 'Gahagan');
insert into subject (name, tutor) values ('Bhangra', 'Shipston');
insert into subject (name, tutor) values ('Business Strategy', 'Tither');
insert into subject (name, tutor) values ('VTP', 'Whalebelly');
insert into subject (name, tutor) values ('Linux System Administration', 'Bumpass');
insert into subject (name, tutor) values ('MQSI', 'Novakovic');
insert into subject (name, tutor) values ('WMOS', 'Rutty');
insert into subject (name, tutor) values ('TTCN-3', 'Fuzzey');
insert into subject (name, tutor) values ('SBEM', 'Couch');
insert into subject (name, tutor) values ('MP2', 'Seiffert');
insert into subject (name, tutor) values ('DBT', 'Musgrave');
insert into subject (name, tutor) values ('MPEG2', 'Rame');
insert into subject (name, tutor) values ('LDPC', 'Phillp');
insert into subject (name, tutor) values ('Tcpdump', 'Novakovic');
insert into subject (name, tutor) values ('IS-IS', 'Elvish');
insert into subject (name, tutor) values ('Scientific Writing', 'Petrasso');
insert into subject (name, tutor) values ('PBIS', 'Loney');
insert into subject (name, tutor) values ('VMware Server', 'Gooly');
insert into subject (name, tutor) values ('NDT', 'Dowle');
insert into subject (name, tutor) values ('Key Person Insurance', 'Pedrielli');
insert into subject (name, tutor) values ('Black &amp; White Photography', 'McIlriach');
insert into subject (name, tutor) values ('Driven By Results', 'Schwandner');
insert into subject (name, tutor) values ('Asset Protection', 'Lamberteschi');
insert into subject (name, tutor) values ('RSS', 'Lymbourne');
insert into subject (name, tutor) values ('Yachting', 'Disley');
insert into subject (name, tutor) values ('Google Earth', 'Junkinson');
insert into subject (name, tutor) values ('Operational Oversight', 'Gertz');
insert into subject (name, tutor) values ('VC#', 'Cleve');
insert into subject (name, tutor) values ('Geometric Dimensioning &amp; Tolerancing', 'Izhakov');
insert into subject (name, tutor) values ('JSA', 'McLukie');
insert into subject (name, tutor) values ('Multi-Unit', 'Burgan');
insert into subject (name, tutor) values ('HP Openview', 'Gillimgham');
insert into subject (name, tutor) values ('Juvenile Justice', 'Wedlake');
insert into subject (name, tutor) values ('Final Cut Pro', 'Sigars');
insert into subject (name, tutor) values ('UCP 600', 'Firpi');
insert into subject (name, tutor) values ('VDA', 'Simeons');
insert into subject (name, tutor) values ('Functional Training', 'Cuningham');
insert into subject (name, tutor) values ('Justice', 'Gallant');
insert into subject (name, tutor) values ('Seismic Attributes', 'Bowich');
insert into subject (name, tutor) values ('Technical Support', 'Edgeller');
insert into subject (name, tutor) values ('Registered Patent Attorney', 'Rodwell');
insert into subject (name, tutor) values ('Akka', 'Kellitt');
insert into subject (name, tutor) values ('Latin America', 'Handslip');
insert into subject (name, tutor) values ('Non-compete Agreements', 'Roostan');
insert into subject (name, tutor) values ('First Year Experience', 'Dorgon');
insert into subject (name, tutor) values ('SDH', 'Pratley');
insert into subject (name, tutor) values ('Amazon RDS', 'Cawsby');
insert into subject (name, tutor) values ('Komodo Edit', 'Grafton-Herbert');
insert into subject (name, tutor) values ('People Skills', 'Blayd');
insert into subject (name, tutor) values ('Award Submissions', 'Riggeard');
insert into subject (name, tutor) values ('Early Intervention', 'Camble');
insert into subject (name, tutor) values ('Graduate Recruitment', 'Edgeson');
insert into subject (name, tutor) values ('LCS', 'Thurske');
insert into subject (name, tutor) values ('Sybase IQ', 'Vibert');
insert into subject (name, tutor) values ('Pitching Ideas', 'Rikkard');
insert into subject (name, tutor) values ('Fertility', 'Radwell');
insert into subject (name, tutor) values ('FTP', 'Oseman');
insert into subject (name, tutor) values ('RPAS', 'Linne');
insert into subject (name, tutor) values ('SAP OM', 'Dutteridge');
insert into subject (name, tutor) values ('UDP', 'Mullen');
insert into subject (name, tutor) values ('DDI', 'Bridgnell');
insert into subject (name, tutor) values ('Sweaters', 'Yallowley');
insert into subject (name, tutor) values ('XBRL', 'Friberg');
insert into subject (name, tutor) values ('Computer System Validation', 'Heggman');
insert into subject (name, tutor) values ('FX Derivatives', 'McKitterick');
insert into subject (name, tutor) values ('Aerial Cinematography', 'Rudledge');
insert into subject (name, tutor) values ('Zen', 'McWhinnie');
insert into subject (name, tutor) values ('Public Safety', 'De Gregorio');
insert into subject (name, tutor) values ('Cellular Communications', 'Tapin');
insert into subject (name, tutor) values ('Employee Handbooks', 'McBratney');
insert into subject (name, tutor) values ('Quality Auditing', 'Pringley');
insert into subject (name, tutor) values ('Nanofabrication', 'Hollibone');
insert into subject (name, tutor) values ('LBO', 'Boteman');
insert into subject (name, tutor) values ('Vulnerability Assessment', 'Pietri');
insert into subject (name, tutor) values ('IDS', 'Gilchrest');
insert into subject (name, tutor) values ('Hummingbird DM', 'Tenwick');
insert into subject (name, tutor) values ('DCN', 'Cordelet');
insert into subject (name, tutor) values ('TGA', 'Radolf');
insert into subject (name, tutor) values ('Skin', 'Bruggeman');
insert into subject (name, tutor) values ('Foreclosures', 'Crummey');
insert into subject (name, tutor) values ('Airports', 'Rowcastle');
insert into subject (name, tutor) values ('Aerospace Industries', 'Taylerson');
insert into subject (name, tutor) values ('Assisting Others', 'Prandi');
insert into subject (name, tutor) values ('iGrafx', 'Dinley');
insert into subject (name, tutor) values ('Hotel Management', 'Luparto');
insert into subject (name, tutor) values ('Ice Cream', 'Verillo');
insert into subject (name, tutor) values ('User Interface', 'Lamborn');
insert into subject (name, tutor) values ('Process Engineering', 'Mowlam');
insert into subject (name, tutor) values ('VSAM', 'Alvar');
insert into subject (name, tutor) values ('Solar PV', 'Dewhurst');
insert into subject (name, tutor) values ('Twitter', 'Aitken');
insert into subject (name, tutor) values ('Japanese Language Proficiency Test', 'Scarlett');
insert into subject (name, tutor) values ('Toyota Production System', 'Aggett');
insert into subject (name, tutor) values ('Knowledge Engineering', 'Ahlf');
insert into subject (name, tutor) values ('Architecture', 'Heinssen');
insert into subject (name, tutor) values ('Corona SDK', 'Ratcliff');
insert into subject (name, tutor) values ('Drug Development', 'Meenehan');
insert into subject (name, tutor) values ('Rock Climbing', 'Timpany');
insert into subject (name, tutor) values ('IPv6', 'Greest');
insert into subject (name, tutor) values ('IBM XIV', 'Standbrooke');
insert into subject (name, tutor) values ('Lighting', 'Preble');
insert into subject (name, tutor) values ('Yahoo Search', 'Saundercock');
insert into subject (name, tutor) values ('Nanomaterials', 'Frantzen');
insert into subject (name, tutor) values ('Business Overhead Expense', 'Begin');
insert into subject (name, tutor) values ('Fiber Optics', 'Arber');
insert into subject (name, tutor) values ('High Availability', 'Eicke');
insert into subject (name, tutor) values ('TNCC Instruction', 'Tumayan');
insert into subject (name, tutor) values ('Qualitative Research', 'Raccio');
insert into subject (name, tutor) values ('FTIR', 'Swendell');
insert into subject (name, tutor) values ('DC-10', 'Pickburn');
insert into subject (name, tutor) values ('Switching', 'Wakes');
insert into subject (name, tutor) values ('PVSyst', 'Kempson');
insert into subject (name, tutor) values ('GNU/Linux', 'Antley');
insert into subject (name, tutor) values ('Health Promotion', 'Sprionghall');
insert into subject (name, tutor) values ('JSON', 'Authers');
insert into subject (name, tutor) values ('VSOE', 'Mattke');
insert into subject (name, tutor) values ('Olive Oil', 'Jones');
insert into subject (name, tutor) values ('Culinary Skills', 'Meggison');
insert into subject (name, tutor) values ('Aircraft Maintenance', 'Mateja');
insert into subject (name, tutor) values ('NCP', 'Davern');
insert into subject (name, tutor) values ('HTRI Software', 'Baszniak');
insert into subject (name, tutor) values ('Automotive', 'Gawthrope');
insert into subject (name, tutor) values ('JFreeChart', 'Spowage');
insert into subject (name, tutor) values ('Jimmy Jib', 'Elloit');
insert into subject (name, tutor) values ('EIGRP', 'Cund');
insert into subject (name, tutor) values ('Guitar', 'Gater');
insert into subject (name, tutor) values ('International Sales', 'Inskipp');
insert into subject (name, tutor) values ('WTO', 'Sawkins');
insert into subject (name, tutor) values ('Biopharmaceuticals', 'Spadoni');
insert into subject (name, tutor) values ('Immunohistochemistry', 'Sabater');
insert into subject (name, tutor) values ('IBM Content Manager', 'Skerme');
insert into subject (name, tutor) values ('IPv6', 'Theobald');
insert into subject (name, tutor) values ('Global Human Resources Management', 'Bolderstone');
insert into subject (name, tutor) values ('Rigging', 'Poxson');
insert into subject (name, tutor) values ('CTI', 'Brennans');
insert into subject (name, tutor) values ('SAP EWM', 'Pleat');
insert into subject (name, tutor) values ('Firewalls', 'Preshaw');
insert into subject (name, tutor) values ('Key Account Management', 'Dericot');
insert into subject (name, tutor) values ('ICD-9', 'Sporle');
insert into subject (name, tutor) values ('TV News Production', 'Schanke');
insert into subject (name, tutor) values ('Boat', 'Stoffler');
insert into subject (name, tutor) values ('ATG CSC', 'Favell');
insert into subject (name, tutor) values ('Energy Efficiency', 'Halbeard');
insert into subject (name, tutor) values ('XML Spy', 'Goulter');
insert into subject (name, tutor) values ('Zumba Instruction', 'Endean');
insert into subject (name, tutor) values ('OLED', 'Chisholm');
insert into subject (name, tutor) values ('e-QIP', 'Gurg');
insert into subject (name, tutor) values ('Klocwork', 'Nuttey');
insert into subject (name, tutor) values ('Komodo Edit', 'Ziebart');
insert into subject (name, tutor) values ('Windows NT', 'Marde');
insert into subject (name, tutor) values ('JConsole', 'Gillani');
insert into subject (name, tutor) values ('Kinesiology', 'Grishagin');
insert into subject (name, tutor) values ('JiBX', 'Morilla');
insert into subject (name, tutor) values ('IT Risk Management', 'Blain');
insert into subject (name, tutor) values ('IBM HTTP Server', 'Mainds');
insert into subject (name, tutor) values ('Security Awareness', 'Blackman');
insert into subject (name, tutor) values ('GPC', 'Grooby');
insert into subject (name, tutor) values ('SGW', 'Wistance');
insert into subject (name, tutor) values ('Mobile Communications', 'Breens');
insert into subject (name, tutor) values ('KXEN', 'Crassweller');
insert into subject (name, tutor) values ('HEC-HMS', 'O''Kelly');
insert into subject (name, tutor) values ('Private Banking', 'Cantua');
insert into subject (name, tutor) values ('XBR', 'Grece');
insert into subject (name, tutor) values ('Ozone', 'Dorant');
insert into subject (name, tutor) values ('JScript', 'Matzeitis');
insert into subject (name, tutor) values ('BMV', 'Grindrod');
insert into subject (name, tutor) values ('NMLS', 'Touson');
insert into subject (name, tutor) values ('System Deployment', 'Borrett');
insert into subject (name, tutor) values ('Pulse Oximetry', 'MacAless');
insert into subject (name, tutor) values ('RT-PCR', 'Rushton');
insert into subject (name, tutor) values ('European Politics', 'Adhams');
insert into subject (name, tutor) values ('RPG II', 'Tapner');
insert into subject (name, tutor) values ('NRP Instruction', 'Quayle');
insert into subject (name, tutor) values ('Laboratory', 'Kunzelmann');
insert into subject (name, tutor) values ('Easily Adaptable', 'McAdam');
insert into subject (name, tutor) values ('Underground Mining', 'Deevey');
insert into subject (name, tutor) values ('7 QC Tools', 'Bertram');
insert into subject (name, tutor) values ('Ventilation', 'Barnicott');
insert into subject (name, tutor) values ('Tax Returns', 'Beecheno');
insert into subject (name, tutor) values ('Mobile Technology', 'Champain');
insert into subject (name, tutor) values ('CCU', 'Linder');
insert into subject (name, tutor) values ('Jerseys', 'Boddington');
insert into subject (name, tutor) values ('BSF', 'Petrussi');
insert into subject (name, tutor) values ('Back Office', 'Dinnage');
insert into subject (name, tutor) values ('Google Docs', 'Di Maria');
insert into subject (name, tutor) values ('Hygiene', 'Glander');
insert into subject (name, tutor) values ('VC#', 'Winsley');
insert into subject (name, tutor) values ('IP', 'De Souza');
insert into subject (name, tutor) values ('Workshops', 'Jodkowski');
insert into subject (name, tutor) values ('Rx', 'Scantleberry');
insert into subject (name, tutor) values ('Genomics', 'Byre');
insert into subject (name, tutor) values ('Corporate Gifts', 'Cowton');
insert into subject (name, tutor) values ('NIR Spectroscopy', 'Olechnowicz');
insert into subject (name, tutor) values ('Music Theory', 'McGrae');
insert into subject (name, tutor) values ('BFD', 'Kingscote');
insert into subject (name, tutor) values ('SX.enterprise', 'Carcass');
insert into subject (name, tutor) values ('CBM', 'Drummond');
insert into subject (name, tutor) values ('LabVIEW', 'Wollrauch');
insert into subject (name, tutor) values ('USDA', 'Cartmell');
insert into subject (name, tutor) values ('HP XP', 'Simm');
insert into subject (name, tutor) values ('Blueprint Reading', 'Bowler');
insert into subject (name, tutor) values ('PML', 'Dabner');
insert into subject (name, tutor) values ('LSF', 'Ricold');
insert into subject (name, tutor) values ('Electronic Payments', 'Kuhnel');
insert into subject (name, tutor) values ('Applied Mathematics', 'Grigg');
insert into subject (name, tutor) values ('Aerobics', 'Potapczuk');
insert into subject (name, tutor) values ('Computer Network Operations', 'Barker');
insert into subject (name, tutor) values ('Apache', 'Gadman');
insert into subject (name, tutor) values ('Chamber Music', 'Letixier');
insert into subject (name, tutor) values ('Atmel AVR', 'Ibanez');
insert into subject (name, tutor) values ('PK', 'Exley');
insert into subject (name, tutor) values ('DH+', 'Guiett');
insert into subject (name, tutor) values ('PWM', 'Inchley');
insert into subject (name, tutor) values ('Web Content', 'Petrakov');
insert into subject (name, tutor) values ('FTR', 'Derr');
insert into subject (name, tutor) values ('BWA', 'Whalebelly');
insert into subject (name, tutor) values ('HCPCS', 'Elston');
insert into subject (name, tutor) values ('Computer Network Operations', 'Genn');
insert into subject (name, tutor) values ('Switchgear', 'Grimshaw');
insert into subject (name, tutor) values ('Telephone Skills', 'Sterte');
insert into subject (name, tutor) values ('Vulcan', 'Traill');
insert into subject (name, tutor) values ('MM modules', 'Cecchetelli');
insert into subject (name, tutor) values ('NMR', 'Wingrove');
insert into subject (name, tutor) values ('Board of Directors', 'Roddy');
insert into subject (name, tutor) values ('CPCU', 'Sanderson');
insert into subject (name, tutor) values ('Google Adwords', 'Patty');
insert into subject (name, tutor) values ('Cashiering', 'Vannuccini');
insert into subject (name, tutor) values ('WCCP', 'Chinn');
insert into subject (name, tutor) values ('DC-10', 'MacNeilley');
insert into subject (name, tutor) values ('Physical Security', 'Jantet');
insert into subject (name, tutor) values ('Osteoporosis', 'Proctor');
insert into subject (name, tutor) values ('Hearings', 'O''Neary');
insert into subject (name, tutor) values ('Legal Issues', 'Skpsey');
insert into subject (name, tutor) values ('Field Work', 'Washington');
insert into subject (name, tutor) values ('Finite Element Analysis', 'Harkins');
insert into subject (name, tutor) values ('Practice CS', 'Lace');
insert into subject (name, tutor) values ('Book Illustration', 'Lander');
insert into subject (name, tutor) values ('XStream', 'Ruck');
insert into subject (name, tutor) values ('Two-way Radio', 'Tosney');
insert into subject (name, tutor) values ('Xcart', 'Durrant');
insert into subject (name, tutor) values ('iWork', 'Coltart');
insert into subject (name, tutor) values ('Swim Instruction', 'Halford');
insert into subject (name, tutor) values ('MDS', 'Di Gregorio');
